services:
  spark-master:
    build:
      context: ./docker/spark
      dockerfile: Dockerfile
    image: my-spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "7077:7077" # port for worker to connect
      - "8082:8080" # web UI
    volumes:
      - ./docker/spark/conf:/opt/bitnami/spark/conf
      - ./src:/opt/spark/app
      - ./data:/opt/spark/data
    networks:
      - common-net
    command: >
      /bin/bash -c "
      echo spark_pass | sudo -S service ssh start &&
      /opt/bitnami/scripts/spark/run.sh
      "

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-worker-1:
    image: my-spark:latest # reuse image built from spark-master
    container_name: spark-worker-1
    depends_on:
      spark-master:
        condition: service_healthy
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=3
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "8083:8081"
    volumes:
      - ./data:/opt/spark/data
    networks:
      - common-net

  # spark-worker-2:
  #   image: my-spark:latest # reuse image built from spark-master
  #   container_name: spark-worker-2
  #   depends_on:
  #     spark-master:
  #       condition: service_healthy
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark-master:7077
  #     - SPARK_WORKER_WEBUI_PORT=8082 # 8081 is used by worker-1
  #     - SPARK_WORKER_MEMORY=2G
  #     - SPARK_WORKER_CORES=2
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #     - SPARK_USER=spark
  #   ports:
  #     - "8084:8082"
  #   networks:
  #     - common-net

networks:
  common-net:
    external: true
